---
- hosts: all
  gather_facts: no
  roles:
    - python

- hosts: all
  roles:
    - role: common
    - role: oracle-java8
    - role: opendj
      opendj_ldif_file: files/testdata.ldif
      opendj_base_dn: dc=ge,dc=co,dc=uk
  become: yes
