---
- name: install apt repositories
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
    update_cache: yes
    validate_certs: false

- name: accept oracle java license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: select

- name: install oracle java8 packages
  apt:
    pkg: '{{ item }}'
    update_cache: yes
  with_items: '{{ packages }}'
  become: yes
