---
- hosts: all
  gather_facts: no
  roles:
    - python

- hosts: all
  roles:
    - role: bastion
      bastion:
        manage_user: ubuntu
        manage_group: ubuntu
        ansible_repo: https://github.com/m4rkw/genomics
        ansible_path: /home/ubuntu/ansible
        ansible_version: master
  become: yes
